inputs_def:
  - handle: region
    description: Input
    json_schema:
      enum:
        - oss-cn-hangzhou
        - " oss-cn-beijing"
        - oss-cn-shanghai
        - oss-us-west-1
        - oss-us-east-1
      ui:options:
        labels:
          - oss-cn-hangzhou
          - " oss-cn-beijing"
          - oss-cn-shanghai
          - oss-us-west-1
          - oss-us-east-1
    value: oss-cn-hangzhou
  - handle: accessKeyId
    json_schema:
      contentMediaType: oomol/secret
      type: string
    value: ${{OO_SECRET:AliCloud,AliCloud,AccessKey_ID}}
  - handle: accessKeySecret
    json_schema:
      contentMediaType: oomol/secret
      type: string
    value: ${{OO_SECRET:AliCloud,AliCloud,AccessKey_Secret}}
  - handle: bucket
    json_schema:
      type: string
    value: oomol-flows
  - handle: localfile
    json_schema:
      type: string
      ui:widget: file
outputs_def:
  - handle: url
    description: Output
    json_schema:
      type: string
      ui:widget: file
  - handle: originFilePath
    json_schema:
      type: string
ui:
  default_width: 450
executor:
  name: nodejs
  options:
    spawn: false
    entry: main.ts
title: oss-upload
icon: ":fa6-solid:upload:"
