inputs_def:
  - handle: accessKeyId
    description: Input
    json_schema:
      contentMediaType: oomol/secret
      type: string
  - handle: accessKeySecret
    json_schema:
      contentMediaType: oomol/secret
      type: string
    value: ""
  - handle: url
    json_schema:
      type: string
    value: ""
  - handle: type
    json_schema:
      enum:
        - General
        - Advanced
      ui:options:
        labels:
          - General
          - Advanced
    value: ""
outputs_def:
  - handle: content
    description: Output
    json_schema:
      type: string
      ui:widget: file
ui:
  default_width: 450
executor:
  name: nodejs
  options:
    spawn: false
    entry: main.ts
title: ocr
icon: ":fa6-solid:book-open-reader:"
